### ISSUE TITLE
Als ADMIN kan ik een gids gebruiker aanmaken, zodat willekeurige mensen niet de ip-car webapp kunnen gebruiken

### ISSUE THREAD

**Issue by faroeq33** [Angelique-Smit/TLE1#46]

**Comment by faroeq33** [comment]
Bij het testen van de admin's gebruiken overzicht was het onduidelijk hoe je account moest aanmaken. 

### Acceptatiecriteria:
- Gegeven dat als gast registreer krijg ik een boodschap dat ik contact moet opnemen met de admin
- Gegeven dat ik admin ben kan ik een gids toevoegen aan het systeem

**Comment by Roel-H** [comment]
Deze feature is nu gemaakt, er was al een story voor.
